version: '3.8'
services:
  localstack:
    image: localstack/localstack
    ports:
      - "4566:4566"  # Port de l'API
      - "4510-4559:4510-4559"  # Ports des services
    environment:
      - SERVICES=s3
      - DEFAULT_REGION=us-east-1
    volumes:
      - localstack_data:/tmp/localstack/data

volumes:
  localstack_data:
